### ISSUE TITLE
Unable get flickr Authorization url with Java 9

### ISSUE THREAD

**Issue by dalacost** [jeremybrooks/SuprSetr#8]
hi, i have a problem to get the flickr Authorization url, the software not start a url on browser, but with the twitter Authorization url works ok (I tested it).  I can't get any log file from /opt/suprsetr to show you some error. 

$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by jeremybrooks** [comment]
Looks like a problem with Java 9. I'll take a look as soon as I can. In the meantime, it works with Java 8. I believe you can set the environment variable INSTALL4J_JAVA_HOME to tell the installer which java home to use.
Thanks for the report!

**Comment by dalacost** [comment]
you right, with Java 8 works ok.

**Comment by StigNygaard** [comment]
Looks like I have the same problem using Java 10 on Windows 10.

C:\>java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

**Comment by jeremybrooks** [comment]
SuprSetr 3.4.0 includes OpenJDK 13. No need to worry about a certain version of Java on your computer.
