### ISSUE TITLE
There Was An Error While Attempting To Authorize

### ISSUE THREAD

**Issue by 2oh1** [jeremybrooks/SuprSetr#9]
I'm using SuprSetr 3.2.0 on a Mac running Mac OS 10.14.6

In SuprSetr preferences, I'm unable to authorize Flickr.  Clicking "Authorize" takes me to a popup that says "De-authorize and exit?"  Clicking Yes closes SuprSetr, but when i reopen it and click Authorize, I get an error: "Response body is incorrect.  Can't extract token and secret..."

**Comment by jeremybrooks** [comment]
Fixed in SuprSetr 3.4.0
